# Generated by Django 2.1 on 2018-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0008_auto_20180806_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='template'),
        ),
    ]
