# Generated by Django 2.1 on 2018-08-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0009_auto_20180806_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardfield',
            old_name='name',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='templatefields',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='haikuapp.Template'),
        ),
    ]
