# Generated by Django 2.1 on 2018-08-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0011_add_user_to_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardfield',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='haikuapp.Card'),
        ),
    ]
