# Generated by Django 2.1 on 2018-08-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0012_add_date_and_time_to_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='imagecard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='haikuapp.Card'),
        ),
    ]
