# Generated by Django 2.1 on 2018-08-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0013_auto_20180807_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_url',
        ),
    ]
