# Generated by Django 2.1 on 2018-08-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0015_auto_20180816_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
