# Generated by Django 2.1 on 2018-08-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0016_template_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='upload_amount',
            field=models.IntegerField(choices=[(0, 'No picture upload'), (1, 'Single picture upload'), (2, 'Multiple picture upload')], default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='upload_required',
            field=models.BooleanField(choices=[(0, 'Picture upload not required'), (1, 'Picture upload required')], default=True),
        ),
    ]
