# Generated by Django 2.1 on 2018-08-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0017_auto_20180816_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='template',
            name='server_image_url',
        ),
        migrations.AddField(
            model_name='template',
            name='server_image',
            field=models.ImageField(blank=True, null=True, upload_to='template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='upload_amount',
            field=models.IntegerField(choices=[(1, 'No picture upload'), (2, 'Single picture upload'), (3, 'Multiple picture upload')], default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='upload_required',
            field=models.BooleanField(choices=[(1, 'Picture upload not required'), (2, 'Picture upload required')], default=True),
        ),
    ]
