# Generated by Django 2.1 on 2018-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0018_auto_20180816_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file_from_server',
            field=models.BooleanField(default=True, verbose_name='Show file from server as picture'),
        ),
    ]
