# Generated by Django 2.1 on 2018-08-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0020_auto_20180816_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='upload_amount',
            field=models.IntegerField(choices=[(1, 'No picture upload'), (2, 'Single picture upload'), (3, 'Multiple picture upload')], default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='upload_required',
            field=models.BooleanField(choices=[(1, 'Picture upload not required'), (2, 'Picture upload required')], default=True),
        ),
    ]
