# Generated by Django 2.1 on 2018-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0021_auto_20180816_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='upload_amount',
            field=models.IntegerField(choices=[(0, 'No picture upload'), (1, 'Single picture upload'), (2, 'Multiple picture upload')], default=0),
        ),
    ]
