# Generated by Django 2.1 on 2018-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0022_auto_20180816_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='upload_required',
            field=models.BooleanField(choices=[(0, 'Picture upload not required'), (1, 'Picture upload required')], default=True),
        ),
    ]
